source 'https://rubygems.org'


gem 'rails', '4.1.8'
gem 'slim-rails'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
# gem 'therubyracer',  platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'spring',        group: :development
gem 'bcrypt', '~> 3.1.7'
gem 'thin'
gem 'awesome_print'
gem 'bootstrap-sass', '~> 3.3.1'
gem 'bootstrap_form'
